// <auto-generated />
using LabtopInfo.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabtopInfo.Migrations
{
    [DbContext(typeof(LabtopsInfoDbContexts))]
    [Migration("20241123092747_new data ")]
    partial class newdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LabtopInfo.Entitis.LabtopCategoris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("laptopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("laptopId");

                    b.ToTable("labtopCategoris");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a test... ",
                            Name = "Rog",
                            laptopId = 1
                        });
                });

            modelBuilder.Entity("LabtopInfo.Entitis.Labtops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("labtops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ",
                            Name = "Asus"
                        });
                });

            modelBuilder.Entity("LabtopInfo.Entitis.LabtopCategoris", b =>
                {
                    b.HasOne("LabtopInfo.Entitis.Labtops", "laptops")
                        .WithMany("labtopCategoris")
                        .HasForeignKey("laptopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("laptops");
                });

            modelBuilder.Entity("LabtopInfo.Entitis.Labtops", b =>
                {
                    b.Navigation("labtopCategoris");
                });
#pragma warning restore 612, 618
        }
    }
}
